<?php

namespace Opencontent\Opendata\Api\AttributeConverter;


use eZContentClassAttribute;
use eZContentObjectAttribute;

class Geo extends Base
{

    public function get( eZContentObjectAttribute $attribute )
    {
        $content = parent::get( $attribute );
        /** @var \eZGmapLocation $attributeContent */
        $attributeContent = $attribute->content();
        $content['content'] = array(
            'latitude' => (float)$attributeContent->attribute( 'latitude' ),
            'longitude' => (float)$attributeContent->attribute( 'longitude' ),
            'address' => $attributeContent->attribute( 'address' )
        );
        return $content;
    }

    public function set( $data )
    {
        return parent::set( $data ); // TODO: Change the autogenerated stub
    }

    public static function validate( $identifier, $data, eZContentClassAttribute $attribute )
    {
        if ( is_array( $data ) )
        {

        }
    }
}