<?php

namespace Opencontent\Opendata\Api\AttributeConverter;


use eZContentClassAttribute;
use eZContentObjectAttribute;

class Keywords extends Base
{

    public function get( eZContentObjectAttribute $attribute )
    {
        $content = parent::get( $attribute );
        /** @var \eZKeyword $attributeContent */
        $attributeContent = $attribute->content();
        $content['content'] = $attributeContent->KeywordArray;
        return $content;
    }

    public function set( $data )
    {
        return parent::set( $data ); // TODO: Change the autogenerated stub
    }

    public static function validate( $identifier, $data, eZContentClassAttribute $attribute )
    {
        parent::validate( $identifier, $data, $attribute ); // TODO: Change the autogenerated stub
    }
}