<?php

namespace Opencontent\Opendata\Api\AttributeConverter;

use eZContentObjectAttribute;
use eZContentClassAttribute;

class Relations extends Base
{

    public function get( eZContentObjectAttribute $attribute )
    {
        return parent::get( $attribute ); // TODO: Change the autogenerated stub
    }

    public function set( $data )
    {
        return parent::set( $data ); // TODO: Change the autogenerated stub
    }

    public static function validate( $identifier, $data, eZContentClassAttribute $attribute )
    {
        parent::validate( $identifier, $data, $attribute ); // TODO: Change the autogenerated stub
    }

    public function type( eZContentClassAttribute $attribute )
    {
        return parent::type( $attribute ); // TODO: Change the autogenerated stub
    }
}